=== ApolloDev/apollo/apollo-ws/schemas/trunk/src/main/resources/base-types/population.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
/*
 * Copyright 2012, University of Pittsburgh
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 -->
 
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://types.apollo.pitt.edu/"
	xmlns:tns="http://types.apollo.pitt.edu/"
	elementFormDefault="qualified">


    <complexType name="simulated_population">
    	<sequence>
    		<element name="location" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="age" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="gender" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<choice><element name="count" type="double" maxOccurs="1" minOccurs="1"></element><element name="subpopulation" type="tns:simulated_population" maxOccurs="unbounded" minOccurs="1">
    		</element></choice>
    	</sequence>
    </complexType>

    <element name="population" type="tns:simulated_population"></element>
</schema>

=== ApolloDev/apollo/apollo-ws/schemas/trunk/src/main/resources/base-types/population.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:population xmlns:tns="http://types.apollo.pitt.edu/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://types.apollo.pitt.edu/ population.xsd ">
	<tns:location>United States of America</tns:location>
	<tns:name>United States of America</tns:name>
	<tns:subpopulation>
		<tns:location>Pennsylvania</tns:location>
		<tns:subpopulation>
			<tns:location>Allegheny County</tns:location>
			<tns:subpopulation>
				<tns:location>15222</tns:location>
				<tns:gender>F</tns:gender>
				<tns:count>211.0</tns:count>
			</tns:subpopulation>
			<tns:subpopulation>
				<tns:location>other</tns:location> <!-- other in Allegheny County -->
				<tns:count>1199779.0</tns:count>
			</tns:subpopulation>
		</tns:subpopulation>
		<tns:subpopulation>
			<tns:location>other</tns:location> <!-- other in PA -->
			<tns:count>12000000.0</tns:count>
		</tns:subpopulation>
	</tns:subpopulation>
	<tns:subpopulation>
		<tns:location>Maine</tns:location>
		<tns:subpopulation>
			<tns:location>Penobscot County</tns:location>
			<tns:subpopulation>
				<tns:location>04401</tns:location>
				<tns:gender>M</tns:gender>
				<tns:count>23.0</tns:count>
			</tns:subpopulation>
			<tns:subpopulation>
				<tns:location>other</tns:location> <!-- other in Penobsoct County -->
				<tns:count>153000.0</tns:count>
			</tns:subpopulation>
		</tns:subpopulation>
		<tns:subpopulation>
			<tns:location>other</tns:location> <!-- other in Maine -->
			<tns:count>1300000</tns:count>
		</tns:subpopulation>
	</tns:subpopulation>
	<tns:subpopulation>
		<tns:location>other</tns:location> <!-- other in US -->
		<tns:count>314070000</tns:count>
	</tns:subpopulation>
</tns:population>
